name: Minimal Test

on:
  workflow_dispatch:
  schedule:
    - cron: '29 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "GitHub Actions werkt!"
